// this file has been auto-generated by cotype seed creation
const data = [];

exports.seed = knex =>
  knex("media")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("media").insert(chunk);
      }, Promise.resolve());
    });
