// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "name": "Administrator",
    "email": "admin@cotype.dev",
    "password": "$2a$10$QiaTRQ18IfeeVp2RgFzsquDqLOWVxpBYjnFl9Wi0XZcHVbhShm..e",
    "picture": null,
    "role": 1,
    "created_at": "2019-07-31 15:27:28",
    "deleted": 0
  }
];

exports.seed = knex =>
  knex("users")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("users").insert(chunk);
      }, Promise.resolve());
    });
