// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "name": "admin",
    "permissions": "{\"settings\":true,\"content\":{\"*\":7}}"
  },
  {
    "id": 2,
    "name": "mixed-access",
    "permissions": "{\"settings\":false,\"content\":{\"foos\":0,\"bars\":\"1\",\"bazs\":\"3\",\"quxs\":\"7\"}}"
  }
];

exports.seed = knex =>
  knex("roles")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("roles").insert(chunk);
      }, Promise.resolve());
    });
