// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "type": "foos",
    "latest_rev": 1,
    "published_rev": 1,
    "deleted": 0
  },
  {
    "id": 2,
    "type": "bars",
    "latest_rev": 1,
    "published_rev": 1,
    "deleted": 0
  },
  {
    "id": 3,
    "type": "bazs",
    "latest_rev": 1,
    "published_rev": 1,
    "deleted": 0
  },
  {
    "id": 4,
    "type": "quxs",
    "latest_rev": 1,
    "published_rev": 1,
    "deleted": 0
  }
];

exports.seed = knex =>
  knex("contents")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("contents").insert(chunk);
      }, Promise.resolve());
    });
