// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "rev": 1,
    "date": "2019-01-24 12:36:53",
    "data": "{\"name\":\"Test Foo\"}",
    "author": 1
  },
  {
    "id": 2,
    "rev": 1,
    "date": "2019-01-24 12:37:01",
    "data": "{\"name\":\"Test Bar\"}",
    "author": 1
  },
  {
    "id": 3,
    "rev": 1,
    "date": "2019-01-24 12:37:09",
    "data": "{\"name\":\"Test Baz\"}",
    "author": 1
  },
  {
    "id": 4,
    "rev": 1,
    "date": "2019-01-24 12:37:18",
    "data": "{\"name\":\"Test Qux\"}",
    "author": 1
  }
];

exports.seed = knex =>
  knex("content_revisions")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("content_revisions").insert(chunk);
      }, Promise.resolve());
    });
