// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "rev": 1,
    "published": 0,
    "field": "name",
    "literal": "Test Foo",
    "numeric": null
  },
  {
    "id": 1,
    "rev": 1,
    "published": 1,
    "field": "name",
    "literal": "Test Foo",
    "numeric": null
  },
  {
    "id": 2,
    "rev": 1,
    "published": 0,
    "field": "name",
    "literal": "Test Bar",
    "numeric": null
  },
  {
    "id": 2,
    "rev": 1,
    "published": 1,
    "field": "name",
    "literal": "Test Bar",
    "numeric": null
  },
  {
    "id": 3,
    "rev": 1,
    "published": 0,
    "field": "name",
    "literal": "Test Baz",
    "numeric": null
  },
  {
    "id": 3,
    "rev": 1,
    "published": 1,
    "field": "name",
    "literal": "Test Baz",
    "numeric": null
  },
  {
    "id": 4,
    "rev": 1,
    "published": 0,
    "field": "name",
    "literal": "Test Qux",
    "numeric": null
  },
  {
    "id": 4,
    "rev": 1,
    "published": 1,
    "field": "name",
    "literal": "Test Qux",
    "numeric": null
  }
];

exports.seed = knex =>
  knex("content_values")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("content_values").insert(chunk);
      }, Promise.resolve());
    });
