// this file has been auto-generated by cotype seed creation
const data = [
  {
    "id": 1,
    "rev": 1,
    "published": 0,
    "text": "test foo"
  },
  {
    "id": 1,
    "rev": 1,
    "published": 1,
    "text": "test foo"
  },
  {
    "id": 2,
    "rev": 1,
    "published": 0,
    "text": "test bar"
  },
  {
    "id": 2,
    "rev": 1,
    "published": 1,
    "text": "test bar"
  },
  {
    "id": 3,
    "rev": 1,
    "published": 0,
    "text": "test baz"
  },
  {
    "id": 3,
    "rev": 1,
    "published": 1,
    "text": "test baz"
  },
  {
    "id": 4,
    "rev": 1,
    "published": 0,
    "text": "test qux"
  },
  {
    "id": 4,
    "rev": 1,
    "published": 1,
    "text": "test qux"
  }
];

exports.seed = knex =>
  knex("content_search")
    .del()
    .then(() => {
      const seedData = [].concat(data);
      const chunks = [];

      while (seedData.length) {
        chunks.push(seedData.splice(0, 100));
      }

      return chunks.reduce(async (memo, chunk) => {
        await memo;

        return knex("content_search").insert(chunk);
      }, Promise.resolve());
    });
