defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: /home/circleci/cotype

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create package-lock.json checksum
          command: >
            sha256sum package-lock.json > .package-lock-sum &&
            sha256sum client/package-lock.json >> .package-lock-sum &&
            sha256sum demo/package-lock.json >> .package-lock-sum
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".package-lock-sum" }}
      - run:
          name: Install
          command: CYPRESS_INSTALL_BINARY=0 npm install
      - save_cache:
          paths:
            - node_modules
            - client/node_modules
            - demo/node_modules
            - models.schema.json
            - navigation.schema.json
          key: v1-dependencies-{{ checksum ".package-lock-sum" }}
      - save_cache:
          paths:
            - ~/cotype
          key: v1-repo-{{ .Revision }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: Test
          command: npm run test -- --coverage
      - save_cache:
          paths:
            - coverage
          key: v1-coverage-{{ .Revision }}
  e2e:
    <<: *defaults
    docker:
      - image: cypress/browsers:chrome69
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-cypress-3.2.0
      - run:
          name: Install cypress
          command: CYPRESS_INSTALL_BINARY=3.2.0 $(npm bin)/cypress install
      - run:
          name: Run cypress
          command: npm run e2e
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - save_cache:
          paths:
            - /root/.cache/Cypress
          key: v1-cypress-3.2.0
  build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - dist
            - lib
            - client/lib
          key: v1-build-{{ .Revision }}
  codecov:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-coverage-{{ .Revision }}
      - run:
          name: Publish Coverage
          command: $(npm bin)/codecov
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run:
          name: Release
          command: $(npm bin)/semantic-release
  pre-release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-build-{{ .Revision }}
      - run:
          name: Pre-Release
          command: $(npm bin)/semantish-prerelease

workflows:
  version: 2
  test-and-publish:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - e2e:
          requires:
            - install
      - build:
          requires:
            - install
      - codecov:
          requires:
            - test
      - release:
          requires:
            - lint
            - test
            - e2e
            - build
          filters:
            branches:
              only: master
      - pre-release:
          requires:
            - lint
            - test
            - e2e
            - build
          filters:
            branches:
              ignore: master
