declare module "@navjobs/upload";
declare module "color-hash";
declare module "javascript-time-ago";
declare module "javascript-time-ago/locale/en";
declare module "react-circular-progressbar";
declare module "react-day-picker/moment";
declare module "react-time-ago";
declare module "rc-input-number";
declare module "mudder";
